name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build examples
      run: ./build.sh

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v4
    - name: 'Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: clang64
        update: true
    - name: build examples
      run: ./build.sh
